### ISSUE TITLE
Just Small Suggestions for the Code Enhancements

### ISSUE THREAD

**Issue by CGCraftsman** [myanmarcyberyouths/breeze-poly#29]
This part could moved to the RegisterRequest since the request should be responsible for 
 -    Defines the validation rules of the HTTP request and executes it.
 -    Small converting of received HTTP parameters(If necessary).
 https://github.com/myanmarcyberyouths/breeze-poly/blob/0df5ec0ccb5931d1fcb2483ef8bdb33d78abb53b/app/Http/Controllers/Api/V1/Auth/AuthController.php#L20-L24

In my opinion, such the global functions break scope of the responsibility(_I understand that it's the Laravel's build in methods_). Plus, these are really hard to test when it comes to the unit testing in my experience(_Some of the Laravel's build in method needs to boot up the application_). So, these global methods should be handled by namespace at least. In our case, we could be able to use through Facades. Then, we could be able to take benefits of the Facade Mocking. 

For the hard coded value, `User has been created successfully`, I would prefer using through Language translation files. 

https://github.com/myanmarcyberyouths/breeze-poly/blob/0df5ec0ccb5931d1fcb2483ef8bdb33d78abb53b/app/Http/Controllers/Api/V1/Auth/AuthController.php#L35-L37

Better to import the `Exception` and use it. 
https://github.com/myanmarcyberyouths/breeze-poly/blob/0df5ec0ccb5931d1fcb2483ef8bdb33d78abb53b/app/Http/Controllers/Api/V1/Auth/AuthController.php#L38

I guess this part is the responsibility of the middleware. 
https://github.com/myanmarcyberyouths/breeze-poly/blob/0df5ec0ccb5931d1fcb2483ef8bdb33d78abb53b/app/Http/Controllers/Api/V1/Auth/AuthController.php#L47-L49

The hard coded value `200` could be change to the explanatory constant from the `Response` class. 
https://github.com/myanmarcyberyouths/breeze-poly/blob/0df5ec0ccb5931d1fcb2483ef8bdb33d78abb53b/app/Http/Controllers/Api/V1/Auth/AuthController.php#L53

If I understand correctly, `60 * 60 * 24` is the the TTL. But, yeah better to extract as explanatory variable or query. Plus, you could able to change the arrow function with the short hand using `fn`. (I _found you use fn at some case, I suggest that one in term of the consistency._) 
https://github.com/myanmarcyberyouths/breeze-poly/blob/0df5ec0ccb5931d1fcb2483ef8bdb33d78abb53b/app/Http/Controllers/Api/V1/Auth/AuthController.php#L64 

`EmailRequest` is not being used in that method. We could remove unnecessary dependencies. 
https://github.com/myanmarcyberyouths/breeze-poly/blob/0df5ec0ccb5931d1fcb2483ef8bdb33d78abb53b/app/Http/Controllers/Api/V1/Auth/EmailValidationController.php#L11

We could remove unnecessary dependency. 
https://github.com/myanmarcyberyouths/breeze-poly/blob/0df5ec0ccb5931d1fcb2483ef8bdb33d78abb53b/app/Http/Controllers/Api/V1/Auth/EmailValidationController.php#L16

I guess it's the typo. 
https://github.com/myanmarcyberyouths/breeze-poly/blob/0df5ec0ccb5931d1fcb2483ef8bdb33d78abb53b/app/Http/Controllers/Api/V1/AuthenicatedUserAactivities/UserActivityFeedController.php#L3

Rather than leaving a comment, I would suggest to refactor a bit. As of the comment mentioned, `5` is the event repost, we could just extract to a explanatory variable.
If I remember correctly, method `get` return the `Eloquent Collection` , when it's passed to the presentation layer it includes `Database Behaviors`. I feels it's not great. The presentation should only know the data structure. In our case, we can simply change to the simple `Collection` using `toBase` method. 
Plus, in my opinion, those kind of query does not very fit with the Active Record. (_`Eloquent` is the implementation of the active record_). Rather than, it could be better if you consider `Table Gateway` or `Repositories`.   
https://github.com/myanmarcyberyouths/breeze-poly/blob/0df5ec0ccb5931d1fcb2483ef8bdb33d78abb53b/app/Http/Controllers/Api/V1/AuthenicatedUserAactivities/UserActivityFeedController.php#L16-L21C21

That method is duplicated in most of the requests. It's breaking the Rule `DRY`. You could be simply extract a base class and make `Is-A` relation using `Inheritance`. 
https://github.com/myanmarcyberyouths/breeze-poly/blob/0df5ec0ccb5931d1fcb2483ef8bdb33d78abb53b/app/Http/Requests/V1/EventRequest.php#L14-L17

### Overall
- Better to use strict types. (Better type system, If I understand correctly, later PHP versions come with the good type system, using type system will worth when the codebase become big). 
- Tests (Unit Tests)
- Tests should be run using pipeline. (Simple github workflow should be okay).

**Comment by amm834** [comment]
Hey @CGCraftsman  I really appreciate your effort on reviewing our code. I am so glad to see your opinion. I am sure, your contribution is valuable for me. Unfortunately, I have no plan to continue this MVP project since we moved to the microservices.
